[theme]
primaryColor = "#10b981"
backgroundColor = "#07090e"
secondaryBackgroundColor = "#0c121e"
textColor = "#e2e8f0"
font = "monospace"
base = "dark"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
